### ISSUE TITLE
Evaluation split & ProteinBert

### ISSUE THREAD

**Issue by ddofer** [google-research/proteinfer#48]
Hi;
1. Cool paper!
2. Re your uniref 50 split - you may want to use the data we provide in our ProteinBert paper - in it we did pretraining on MLM as well as predicting all GO terms, over all uniref90, and split the validation/test sets more stringently, as well as by similarity to downstream evaluation benchmarks (TAPE).  The datasets are downloadable from the FTP, along with the model (a citation would be nice :)). 
https://github.com/nadavbra/protein_bert

> Brandes, N., Ofer, D., Peleg, Y., Rappoport, N. & Linial, M. ProteinBERT: A universal deep-learning model of protein sequence and function. bioRxiv (2021). https://doi.org/10.1101/2021.05.24.445464

Good luck!

**Comment by theosanderson** [comment]
Thank you for the kind words, and for the pointer to your very interesting work. We'll cite it in the next version of the paper when discussing recent work on pretraining, and when discussing alternative train-test splits
