### ISSUE TITLE
How can i get the 3D molecule from your prediction result?

### ISSUE THREAD

**Issue by TYoung1221** [google-research/proteinfer#55]

**Comment by theosanderson** [comment]
Hi @TYoung1221, ProteInfer predicts functions from amino acid sequences, but does not predict 3D structures. On our website we show some structures from [the PDB](https://www.rcsb.org/) for specific proteins to illustrate in 3D which parts of a protein's sequence are used to make a particular prediction – often corresponding to known domains, but this is not available for custom sequences, in part as many of these will not be covered in the PDB. For structure prediction you may want to try a tool such as [AlphaFold](https://github.com/deepmind/alphafold).
