### ISSUE TITLE
Updating Security Measures

### ISSUE THREAD

**Issue by singhaditya28** [google-research/proteinfer#6]
Dear Authors ,
Hope you're doing well 😃  !

I found out this project and immediately realised its potential. I want to update the project with some secure syntax. Can I get the names of the **python** files which are standalone and not being imported to other files so that I can create a dedicated PR ? Thanks in advance. 👍

PS :: I will try my best to make this project a success.

**Comment by theosanderson** [comment]
Hi @singhaditya28, thank you very much for this offer. Unfortunately we are not able to take pull requests at this time as this is a work-in-progress repo in which internal code is being open-sourced. We have now updated the README.md to fully explain this. Thank you again for taking the time to think about these issues. 

Stay tuned for future updates to this repo.
