### ISSUE TITLE
installing python dependencies not working :(

### ISSUE THREAD

**Issue by pratheekpandesha** [google-research/proteinfer#60]
Hello,
First of all thanks a lot for this great tool!!
I'm trying to run your codes for a month or so- there were several errors showing up. I could see you have made a couple of changes recently- I appreciate it! But "Get our code from GitHub and install python dependencies" is still not working and it seems there are some changes in the python repository.
Are you still working on those? if you think it is a concern that can be overcome please could you let me know?? 
That would be of great help!

**Comment by theosanderson** [comment]
Thank you for flagging this @pratheekpandesha. A new release of protobuf forced us to pin that, but I think there was an issue with the way we pinned it. Hopefully this is fixed in #61 . Let us know if you continue to have issues.
